name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # senin branch adın main ise, değilse master yaz

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # index.html kökte olduğu için burası nokta (.)
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
